[package]
name = "conrad-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1", features = ["sqlite"] }
diesel_migrations = { version = "2.1", features = ["sqlite"] }
dotenvy = "0.15"
thiserror = "1.0.40"
