[package]
name = "conrad"
version = "0.1.0"
edition = "2021"

[features]
oauth = ["dep:conrad-oauth"]

[dependencies]
conrad-core = { path = "../conrad-core", version = "0.1.0" }
conrad-oauth = { path = "../conrad-oauth", version = "0.1.0", optional = true }
