[package]
name = "conrad-tokens"
version = "0.1.0"
edition = "2021"

[dependencies]
conrad-core = { path = "../conrad-core", version = "0.1.0" }
futures = "0.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
uuid = { version = "1.3", features = ["v4"] }
