[package]
name = "diesel-adapter"
version = "0.1.0"
edition = "2021"

[features]
postgres = ["diesel/postgres"]
mysql = ["diesel/mysql"]
sqlite = ["diesel/sqlite"]

[dependencies]
conrad-core = { path = "../conrad-core", version = "0.1.0" }
diesel = "2.1"
